# Rampart linter configuration.
# Enforces tight, readable, purpose-driven code.

run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - gocritic
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - revive

linters-settings:
  gocritic:
    enabled-checks:
      - appendAssign
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - elseif
      - emptyFallthrough
      - equalFold
      - hugeParam
      - nestingReduce
      - rangeValCopy
      - sloppyLen
      - truncateCmp
      - underef
      - unnamedResult
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: exported
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: var-naming

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
