version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: rampart
    main: ./cmd/rampart
    binary: rampart
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/peg/rampart/internal/build.Version={{.Version}}
      - -X github.com/peg/rampart/internal/build.Commit={{.Commit}}
      - -X github.com/peg/rampart/internal/build.Date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "rampart_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"

release:
  github:
    owner: peg
    name: rampart
  prerelease: auto

# Homebrew tap auto-update on release.
# Requires HOMEBREW_TAP_GITHUB_TOKEN secret in GitHub Actions — a PAT with repo scope
# that has write access to the peg/homebrew-rampart repository.
brews:
  - directory: Formula
    repository:
      owner: peg
      name: homebrew-rampart
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://rampart.sh"
    description: "Open-source firewall for AI agents"
    license: "Apache-2.0"
    install: |
      bin.install "rampart"
    test: |
      system "#{bin}/rampart", "version"
