project_name: rampart

builds:
  - id: rampart
    main: ./cmd/rampart
    binary: rampart
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/peg/rampart/internal/build.Version={{.Version}} -X github.com/peg/rampart/internal/build.Commit={{.Commit}} -X github.com/peg/rampart/internal/build.Date={{.Date}}

archives:
  - id: rampart
    builds:
      - rampart
    format: tar.gz
    format_overrides:
      - goos: darwin
        format: zip

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^Merge '
      - '^Revert '
      - '^docs:'
      - '^test:'
      - '^chore:'
