// Copyright 2026 The Rampart Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cli

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/peg/rampart/internal/audit"
	"github.com/peg/rampart/internal/engine"
	"gopkg.in/yaml.v3"
)

// fromAuditOptions holds flags for the --from-audit subflow.
type fromAuditOptions struct {
	auditPath string
	since     string
	dryRun    bool
	output    string
	merge     bool
}

// runInitFromAudit generates policy YAML from audit log events.
// This is the "learn mode → enforce mode" pattern: observe what an agent
// does, then generate rules that match that behavior.
func runInitFromAudit(w io.Writer, opts fromAuditOptions) error {
	events, err := loadAndFilterEvents(opts)
	if err != nil {
		return err
	}

	if len(events) == 0 {
		fmt.Fprintln(w, "\n  No audit events found. Run your agent first, then try again.")
		return nil
	}

	// Only generate rules for allowed events — denied events represent
	// behavior we don't want to codify.
	allowed := filterAllowedEvents(events)
	if len(allowed) == 0 {
		fmt.Fprintf(w, "\n  Found %d events, but none were allowed. Nothing to generate.\n", len(events))
		return nil
	}

	rules := generateRulesFromEvents(allowed)
	content := marshalGeneratedPolicy(rules, opts.auditPath)

	printAuditSummary(w, events, allowed, rules)

	if opts.dryRun {
		fmt.Fprintln(w, "\n  --- Dry run: generated policy ---")
		fmt.Fprintln(w, content)
		return nil
	}

	return writeGeneratedPolicy(w, content, opts.output)
}

// loadAndFilterEvents reads audit events and applies --since filtering.
func loadAndFilterEvents(opts fromAuditOptions) ([]audit.Event, error) {
	events, err := readAuditPath(opts.auditPath)
	if err != nil {
		return nil, err
	}
	if opts.since != "" {
		return filterEventsSince(events, opts.since)
	}
	return events, nil
}

// marshalGeneratedPolicy serializes rules to YAML with a header comment.
func marshalGeneratedPolicy(rules []generatedRule, source string) string {
	cfg := buildPolicyConfig(rules)
	out, _ := yaml.Marshal(cfg) // cfg is always valid, marshal won't fail
	return fmt.Sprintf("# Generated by: rampart init --from-audit\n# Source: %s\n# Generated: %s\n# Review these rules before enforcing.\n\n%s",
		source, time.Now().UTC().Format(time.RFC3339), out)
}

// writeGeneratedPolicy writes the policy file and prints next steps.
func writeGeneratedPolicy(w io.Writer, content, output string) error {
	outputPath, err := resolveAuditOutputPath(output)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return fmt.Errorf("init: from-audit: create dir: %w", err)
	}
	if err := os.WriteFile(outputPath, []byte(content), 0o600); err != nil {
		return fmt.Errorf("init: from-audit: write: %w", err)
	}

	fmt.Fprintf(w, "\n  Written to: %s\n", outputPath)
	fmt.Fprintln(w, "\n  Next steps:")
	fmt.Fprintf(w, "    1. Review the generated rules: cat %s\n", outputPath)
	fmt.Fprintln(w, "    2. Restart rampart to enforce: rampart serve")
	fmt.Fprintln(w, "    3. Refine rules as needed: rampart allow/block")
	return nil
}

// readAuditPath reads all events from a JSONL audit file or directory.
func readAuditPath(path string) ([]audit.Event, error) {
	info, err := os.Stat(path)
	if err != nil {
		return nil, fmt.Errorf("init: from-audit: %w", err)
	}

	if !info.IsDir() {
		events, _, err := audit.ReadEventsFromOffset(path, 0)
		if err != nil {
			return nil, fmt.Errorf("init: from-audit: read %s: %w", path, err)
		}
		return events, nil
	}

	// Directory: read all .jsonl files.
	var allEvents []audit.Event
	entries, err := os.ReadDir(path)
	if err != nil {
		return nil, fmt.Errorf("init: from-audit: read dir: %w", err)
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".jsonl") {
			continue
		}
		fp := filepath.Join(path, entry.Name())
		events, _, err := audit.ReadEventsFromOffset(fp, 0)
		if err != nil {
			continue // skip unreadable files
		}
		allEvents = append(allEvents, events...)
	}
	return allEvents, nil
}

// filterEventsSince filters events to those after now-duration.
func filterEventsSince(events []audit.Event, since string) ([]audit.Event, error) {
	dur, err := time.ParseDuration(since)
	if err != nil {
		return nil, fmt.Errorf("init: from-audit: invalid --since %q: %w", since, err)
	}

	cutoff := time.Now().UTC().Add(-dur)
	var filtered []audit.Event
	for _, e := range events {
		if e.Timestamp.After(cutoff) {
			filtered = append(filtered, e)
		}
	}
	return filtered, nil
}

// filterAllowedEvents returns only events with action=allow.
func filterAllowedEvents(events []audit.Event) []audit.Event {
	var allowed []audit.Event
	for _, e := range events {
		if e.Decision.Action == "allow" {
			allowed = append(allowed, e)
		}
	}
	return allowed
}

// ruleKey uniquely identifies a deduplicated rule.
type ruleKey struct {
	tool    string
	pattern string
}

// generatedRule holds a deduplicated rule ready for policy generation.
type generatedRule struct {
	tool    string
	pattern string
	count   int
}

// generateRulesFromEvents deduplicates audit events into policy rules.
func generateRulesFromEvents(events []audit.Event) []generatedRule {
	seen := make(map[ruleKey]*generatedRule)

	for _, e := range events {
		call := eventToToolCall(e)
		pattern := patternForCall(call)

		key := ruleKey{tool: call.Tool, pattern: pattern}
		if r, ok := seen[key]; ok {
			r.count++
		} else {
			seen[key] = &generatedRule{tool: call.Tool, pattern: pattern, count: 1}
		}
	}

	// Sort by tool then pattern for stable output.
	rules := make([]generatedRule, 0, len(seen))
	for _, r := range seen {
		rules = append(rules, *r)
	}
	sort.Slice(rules, func(i, j int) bool {
		if rules[i].tool != rules[j].tool {
			return rules[i].tool < rules[j].tool
		}
		return rules[i].pattern < rules[j].pattern
	})

	return rules
}

// eventToToolCall converts an audit event to an engine.ToolCall.
func eventToToolCall(e audit.Event) engine.ToolCall {
	return engine.ToolCall{
		Tool:   e.Tool,
		Params: e.Request,
	}
}

// patternForCall generalizes a specific tool call into a reusable glob pattern.
// For exec: "npm install express" → "npm install *" (via GeneralizeCommand).
// For fs: "/home/user/project/src/main.go" → "/home/user/project/src/**".
// For MCP/other: wildcard match on the tool name.
func patternForCall(call engine.ToolCall) string {
	switch call.Tool {
	case "exec":
		return engine.GeneralizeCommand(call.Command())
	case "read", "write", "edit":
		p := call.Path()
		if p == "" {
			return "**"
		}
		// Generalize individual files to directory globs — a policy for
		// "allow reads in src/" is more useful than one per file.
		dir := filepath.Dir(p)
		if dir == "." || dir == "/" {
			return p
		}
		return dir + "/**"
	default:
		return "*"
	}
}

// These types are intentionally separate from engine.Config — they produce
// clean, minimal YAML output without the engine's internal fields (Priority,
// Enabled, Source, Webhook, Ask, etc). Same pattern as marshalCleanYAML
// in persist.go.
type policyEntry struct {
	Name  string        `yaml:"name"`
	Match policyMatch   `yaml:"match"`
	Rules []policyRule  `yaml:"rules"`
}

type policyMatch struct {
	Tool []string `yaml:"tool"`
}

type policyRule struct {
	Action string          `yaml:"action"`
	When   policyCondition `yaml:"when"`
}

type policyCondition struct {
	CommandMatches []string `yaml:"command_matches,omitempty"`
	PathMatches    []string `yaml:"path_matches,omitempty"`
	Default        bool     `yaml:"default,omitempty"`
}

type generatedConfig struct {
	Version       string        `yaml:"version"`
	DefaultAction string        `yaml:"default_action"`
	Policies      []policyEntry `yaml:"policies"`
}

// buildPolicyConfig creates a policy config from generated rules.
func buildPolicyConfig(rules []generatedRule) generatedConfig {
	// Group rules by tool type.
	byTool := make(map[string][]generatedRule)
	for _, r := range rules {
		byTool[r.tool] = append(byTool[r.tool], r)
	}

	cfg := generatedConfig{
		Version:       "1",
		DefaultAction: "deny",
	}

	// Sort tool keys for stable output.
	tools := make([]string, 0, len(byTool))
	for t := range byTool {
		tools = append(tools, t)
	}
	sort.Strings(tools)

	for _, tool := range tools {
		toolRules := byTool[tool]
		entry := policyEntry{
			Name:  fmt.Sprintf("generated-%s-rules", tool),
			Match: policyMatch{Tool: []string{tool}},
		}

		for _, r := range toolRules {
			pr := policyRule{Action: "allow"}
			switch tool {
			case "exec":
				pr.When.CommandMatches = []string{r.pattern}
			case "read", "write", "edit":
				pr.When.PathMatches = []string{r.pattern}
			default:
				pr.When.Default = true
			}
			entry.Rules = append(entry.Rules, pr)
		}

		cfg.Policies = append(cfg.Policies, entry)
	}

	return cfg
}

// printAuditSummary prints a human-readable summary of what was generated.
func printAuditSummary(w io.Writer, all, allowed []audit.Event, rules []generatedRule) {
	// Count unique sessions.
	sessions := make(map[string]bool)
	for _, e := range all {
		if e.Session != "" {
			sessions[e.Session] = true
		}
	}

	fmt.Fprintf(w, "\n  Analyzed %d tool calls", len(all))
	if len(sessions) > 0 {
		fmt.Fprintf(w, " across %d session(s)", len(sessions))
	}
	fmt.Fprintln(w)

	// Count rules by tool type.
	toolCounts := make(map[string]int)
	toolExamples := make(map[string][]string)
	for _, r := range rules {
		toolCounts[r.tool]++
		if len(toolExamples[r.tool]) < 3 {
			toolExamples[r.tool] = append(toolExamples[r.tool], r.pattern)
		}
	}

	fmt.Fprintf(w, "\n  Generated %d rules:\n", len(rules))
	tools := make([]string, 0, len(toolCounts))
	for t := range toolCounts {
		tools = append(tools, t)
	}
	sort.Strings(tools)

	for _, tool := range tools {
		examples := strings.Join(toolExamples[tool], ", ")
		if len(examples) > 50 {
			examples = examples[:47] + "..."
		}
		fmt.Fprintf(w, "    %-6s %d patterns  (%s)\n", tool, toolCounts[tool], examples)
	}
}

// resolveAuditOutputPath determines the output file path.
func resolveAuditOutputPath(output string) (string, error) {
	if output != "" {
		return output, nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("init: from-audit: resolve home: %w", err)
	}
	return filepath.Join(home, ".rampart", "policies", "generated.yaml"), nil
}
