package cli

import (
	"strings"
	"testing"

	"github.com/peg/rampart/internal/detect"
)

func TestGenerateTailoredPolicy(t *testing.T) {
	// Basic case
	result := &detect.DetectResult{}
	data, err := generateTailoredPolicy(result)
	if err != nil {
		t.Fatal(err)
	}
	if len(data) == 0 {
		t.Fatal("empty policy")
	}
	if !strings.Contains(string(data), "Generated by rampart init") {
		t.Error("missing header comment")
	}

	// With kubectl
	result.HasKubectl = true
	data, err = generateTailoredPolicy(result)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "block-kubectl-dangerous") {
		t.Error("missing kubectl rules")
	}

	// With docker
	result.HasDocker = true
	data, err = generateTailoredPolicy(result)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "block-docker-dangerous") {
		t.Error("missing docker rules")
	}
}
