// Copyright 2026 The Rampart Authors
// Licensed under the Apache License, Version 2.0

package audit

import (
	"bytes"
	"context"
	"crypto/ed25519"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

const witnessRecordLimit = 16 << 10
const maxWitnessReceipts = 100000

var witnessIdentifier = regexp.MustCompile(`^[a-z0-9][a-z0-9_-]{15,63}$`)

// WitnessConfig is operator-owned configuration. Keep an independent copy of
// the chain identity and key pins: audit metadata is never an identity authority.
type WitnessConfig struct {
	Version       int               `json:"version"`
	ChainID       string            `json:"chain_id"`
	WitnessID     string            `json:"witness_id"`
	URL           string            `json:"url,omitempty"`
	TokenFile     string            `json:"token_file,omitempty"`
	Keys          map[string]string `json:"keys,omitempty"`
	FileDirectory string            `json:"file_directory,omitempty"`
	MaxAgeSeconds int64             `json:"max_age_seconds,omitempty"`
}

// WitnessCheckpoint deliberately excludes event IDs, paths, host names and
// action data. A hash commits to recorded history, not execution completeness.
type WitnessCheckpoint struct {
	Version    int       `json:"version"`
	ChainID    string    `json:"chain_id"`
	EventCount int64     `json:"event_count"`
	Hash       string    `json:"hash"`
	CreatedAt  time.Time `json:"created_at"`
}

// WitnessReceipt is the HTTPS witness's authenticated acceptance statement.
// Signatures cover the domain prefix plus JSON of WitnessAcceptance in field
// order. No private witness signing key is stored or generated by Rampart.
type WitnessAcceptance struct {
	Version    int               `json:"version"`
	WitnessID  string            `json:"witness_id"`
	Checkpoint WitnessCheckpoint `json:"checkpoint"`
	AcceptedAt time.Time         `json:"accepted_at"`
	KeyID      string            `json:"key_id"`
}

type WitnessReceipt struct {
	WitnessAcceptance
	Signature string `json:"signature"`
}

func (a WitnessAcceptance) signingBytes() []byte {
	data, _ := json.Marshal(a)
	return append([]byte("rampart.audit.witness.receipt.v1\n"), data...)
}

// WitnessResult keeps prefix integrity, freshness and delivery separate.
// Verified always means verification under the configured destination's trust
// contract; file storage independence cannot be established by this process.
type WitnessResult struct {
	Status         string `json:"status"`
	Verified       bool   `json:"verified"`
	Authentication string `json:"authentication,omitempty"`
	LocalEvents    int64  `json:"local_events,omitempty"`
	WitnessEvents  int64  `json:"witness_events,omitempty"`
	Unwitnessed    int64  `json:"unwitnessed_events,omitempty"`
	Delivery       string `json:"delivery,omitempty"`
	LastFailure    string `json:"last_failure,omitempty"`
}

type witnessFailure string

func (e witnessFailure) Error() string { return "audit witness: " + string(e) }

// WitnessCode returns a safe classification without disclosing transport
// URLs, credentials, remote response bodies or local audit record content.
func WitnessCode(err error) string {
	var failure witnessFailure
	if errors.As(err, &failure) {
		return string(failure)
	}
	return "local_invalid"
}

type Witness struct {
	config WitnessConfig
	keys   map[string]ed25519.PublicKey
	client *http.Client
	now    func() time.Time
}

func LoadWitness(path string) (*Witness, error) {
	data, err := readWitnessFile(path)
	if err != nil {
		return nil, fmt.Errorf("audit witness: cannot read operator configuration")
	}
	var cfg WitnessConfig
	if err := decodeWitnessJSON(data, &cfg); err != nil {
		return nil, fmt.Errorf("audit witness: invalid operator configuration")
	}
	return NewWitness(cfg)
}

func NewWitness(cfg WitnessConfig) (*Witness, error) {
	if cfg.Version != 1 || !witnessIdentifier.MatchString(cfg.ChainID) || !witnessIdentifier.MatchString(cfg.WitnessID) {
		return nil, fmt.Errorf("audit witness: version 1 and pinned lowercase chain/witness identifiers (16–64 characters) are required")
	}
	if cfg.MaxAgeSeconds == 0 {
		cfg.MaxAgeSeconds = 86400
	}
	if cfg.MaxAgeSeconds < 60 || cfg.MaxAgeSeconds > 365*86400 {
		return nil, fmt.Errorf("audit witness: max_age_seconds must be between 60 and 31536000")
	}
	w := &Witness{config: cfg, keys: make(map[string]ed25519.PublicKey), now: time.Now,
		client: &http.Client{Timeout: 10 * time.Second, CheckRedirect: func(*http.Request, []*http.Request) error {
			return http.ErrUseLastResponse
		}}}
	if cfg.FileDirectory != "" {
		if cfg.URL != "" || cfg.TokenFile != "" || len(cfg.Keys) != 0 {
			return nil, fmt.Errorf("audit witness: choose file storage or authenticated HTTPS")
		}
		if !filepath.IsAbs(cfg.FileDirectory) {
			return nil, fmt.Errorf("audit witness: file destination must be an absolute operator-pinned path")
		}
		if err := validateAuditDirectory(cfg.FileDirectory); err != nil {
			return nil, fmt.Errorf("audit witness: file destination must be an existing non-symlink directory")
		}
		return w, nil
	}
	endpoint, err := url.Parse(cfg.URL)
	if err != nil || endpoint.Scheme != "https" || endpoint.Host == "" || endpoint.User != nil || endpoint.RawQuery != "" || endpoint.Fragment != "" || !filepath.IsAbs(cfg.TokenFile) || len(cfg.Keys) == 0 {
		return nil, fmt.Errorf("audit witness: HTTPS endpoint, separate token file and pinned witness keys are required")
	}
	for id, encoded := range cfg.Keys {
		key, err := base64.StdEncoding.DecodeString(encoded)
		if id == "" || len(id) > 64 || err != nil || len(key) != ed25519.PublicKeySize {
			return nil, fmt.Errorf("audit witness: invalid pinned witness key")
		}
		w.keys[id] = ed25519.PublicKey(key)
	}
	return w, nil
}

func validWitnessCheckpoint(c WitnessCheckpoint, chainID string, now time.Time) bool {
	hash, err := hex.DecodeString(strings.TrimPrefix(c.Hash, "sha256:"))
	_, offset := c.CreatedAt.Zone()
	return c.Version == 1 && c.ChainID == chainID && c.EventCount > 0 &&
		err == nil && len(hash) == 32 && "sha256:"+hex.EncodeToString(hash) == c.Hash &&
		!c.CreatedAt.IsZero() && offset == 0 && !c.CreatedAt.After(now.Add(5*time.Minute))
}

func (w *Witness) validateReceipt(receipt WitnessReceipt) error {
	now := w.now()
	_, offset := receipt.AcceptedAt.Zone()
	if receipt.Version != 1 || receipt.WitnessID != w.config.WitnessID ||
		!validWitnessCheckpoint(receipt.Checkpoint, w.config.ChainID, now) ||
		receipt.AcceptedAt.IsZero() || offset != 0 || receipt.AcceptedAt.After(now.Add(5*time.Minute)) ||
		receipt.AcceptedAt.Before(receipt.Checkpoint.CreatedAt.Add(-5*time.Minute)) {
		return witnessFailure("malformed")
	}
	key, pinned := w.keys[receipt.KeyID]
	signature, err := base64.StdEncoding.DecodeString(receipt.Signature)
	if !pinned || err != nil || !ed25519.Verify(key, receipt.WitnessAcceptance.signingBytes(), signature) {
		return witnessFailure("unauthenticated")
	}
	return nil
}

func (w *Witness) retrieve(ctx context.Context) ([]WitnessReceipt, error) {
	if w.config.FileDirectory != "" {
		return w.retrieveFileHistory(ctx)
	}
	return w.retrieveHTTPS(ctx)
}

func (w *Witness) snapshot(ctx context.Context, dir string, receipts []WitnessReceipt) (recoveredChainState, error) {
	snapshot, err := captureWitnessSnapshot(ctx, dir)
	if err != nil {
		if ctx.Err() != nil {
			return recoveredChainState{}, witnessFailure("verification_incomplete")
		}
		return recoveredChainState{}, witnessFailure("local_invalid")
	}
	checkpoints := make(map[int64]string, len(receipts))
	for _, receipt := range receipts {
		checkpoints[receipt.Checkpoint.EventCount] = receipt.Checkpoint.Hash
	}
	state, err := snapshot.recover(ctx, checkpoints)
	if err != nil {
		if ctx.Err() != nil {
			return recoveredChainState{}, witnessFailure("verification_incomplete")
		}
		return recoveredChainState{}, witnessFailure("local_invalid")
	}
	if state.rootCount > 1 {
		return recoveredChainState{}, witnessFailure("unsupported_legacy_epochs")
	}
	return state, nil
}

func (w *Witness) compare(state recoveredChainState, receipt WitnessReceipt) (WitnessResult, error) {
	result := WitnessResult{LocalEvents: state.eventCount, WitnessEvents: receipt.Checkpoint.EventCount, Authentication: "signed_https"}
	at := receipt.AcceptedAt
	if w.config.FileDirectory != "" {
		result.Authentication = "separately_administered_storage"
		at = receipt.Checkpoint.CreatedAt // A publisher timestamp, not an independent acceptance time.
	}
	switch {
	case receipt.Checkpoint.EventCount > state.eventCount:
		result.Status = "witness_ahead"
	case state.witnessMismatch || state.prefixHash != receipt.Checkpoint.Hash:
		result.Status = "hash_mismatch"
	case w.now().Sub(at) > time.Duration(w.config.MaxAgeSeconds)*time.Second:
		result.Status = "stale_checkpoint"
	default:
		result.Status = "witnessed_head"
		result.Unwitnessed = state.eventCount - receipt.Checkpoint.EventCount
		if result.Unwitnessed > 0 {
			result.Status = "witnessed_prefix"
		}
		result.Verified = true
		return result, nil
	}
	return result, witnessFailure(result.Status)
}

// Verify always retrieves evidence from the configured independent destination.
// The local delivery cache never supplies proof or establishes chain identity.
func (w *Witness) Verify(ctx context.Context, dir string) (WitnessResult, error) {
	receipts, err := w.retrieve(ctx)
	if err != nil {
		return WitnessResult{Status: WitnessCode(err)}, err
	}
	state, err := w.snapshot(ctx, dir, receipts)
	if err != nil {
		return WitnessResult{Status: WitnessCode(err)}, err
	}
	result, err := w.compare(state, receipts[len(receipts)-1])
	w.addDelivery(dir, &result)
	return result, err
}

// Publish exports only a verified head. It is deliberately separate from the
// sink and performs all transport work outside the audit directory lock.
func (w *Witness) Publish(ctx context.Context, dir string) (result WitnessResult, err error) {
	defer func() {
		result.Delivery = "delivered"
		if err != nil && WitnessCode(err) != "stale_checkpoint" {
			result.Delivery, result.LastFailure = "degraded", WitnessCode(err)
			if result.Status == "" {
				result.Status = result.LastFailure
			}
		}
		if stateErr := w.saveDelivery(dir, result); stateErr != nil {
			result.Delivery, result.LastFailure = "unknown", "delivery_state_unavailable"
			if err == nil {
				err = witnessFailure("delivery_state_unavailable")
			}
		}
	}()
	history, retrieveErr := w.retrieve(ctx)
	if retrieveErr != nil && WitnessCode(retrieveErr) != "no_evidence" {
		return result, retrieveErr
	}
	state, err := w.snapshot(ctx, dir, history)
	if err != nil {
		return result, err
	}
	if state.eventCount == 0 {
		return result, witnessFailure("empty_chain")
	}
	if retrieveErr == nil {
		previous := history[len(history)-1]
		result, err = w.compare(state, previous)
		if err != nil && WitnessCode(err) != "stale_checkpoint" {
			return result, err
		}
		if state.eventCount == previous.Checkpoint.EventCount {
			return result, err // Duplicate publication retains the original acceptance time.
		}
	}
	checkpoint := WitnessCheckpoint{Version: 1, ChainID: w.config.ChainID,
		EventCount: state.eventCount, Hash: state.lastHash, CreatedAt: w.now().UTC()}
	var accepted WitnessReceipt
	if w.config.FileDirectory != "" {
		accepted, err = w.publishFile(checkpoint)
	} else {
		data, _ := json.Marshal(checkpoint)
		accepted, err = w.publishHTTPS(ctx, data)
	}
	if err != nil {
		return WitnessResult{}, err
	}
	if accepted.Checkpoint.EventCount != checkpoint.EventCount || accepted.Checkpoint.Hash != checkpoint.Hash {
		return WitnessResult{}, witnessFailure("conflict")
	}
	state.prefixHash = state.lastHash
	return w.compare(state, accepted)
}

func readWitnessFile(path string) ([]byte, error) {
	file, err := openAuditRegular(path, os.O_RDONLY)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	data, err := io.ReadAll(io.LimitReader(file, witnessRecordLimit+1))
	if err != nil || len(data) > witnessRecordLimit {
		return nil, witnessFailure("malformed")
	}
	return data, nil
}

func decodeWitnessJSON(data []byte, target any) error {
	if len(data) > witnessPageLimit {
		return witnessFailure("malformed")
	}
	// Reject ambiguous object members before decoding the known boundary type.
	decoder := json.NewDecoder(bytes.NewReader(data))
	var value func(int) error
	value = func(depth int) error {
		if depth > 8 {
			return witnessFailure("malformed")
		}
		token, err := decoder.Token()
		if err != nil {
			return err
		}
		if token == json.Delim('{') {
			seen := make(map[string]bool)
			for decoder.More() {
				key, err := decoder.Token()
				name, ok := key.(string)
				if err != nil || !ok || seen[name] {
					return witnessFailure("malformed")
				}
				seen[name] = true
				if err := value(depth + 1); err != nil {
					return err
				}
			}
			_, err = decoder.Token()
		} else if token == json.Delim('[') {
			for decoder.More() {
				if err := value(depth + 1); err != nil {
					return err
				}
			}
			_, err = decoder.Token()
		}
		return err
	}
	if err := value(0); err != nil {
		return witnessFailure("malformed")
	}
	decoder = json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(target); err != nil {
		return witnessFailure("malformed")
	}
	if err := decoder.Decode(new(any)); !errors.Is(err, io.EOF) {
		return witnessFailure("malformed")
	}
	return nil
}
