// Copyright 2026 The Rampart Authors
// Licensed under the Apache License, Version 2.0 (the "License").

package generate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func TestAllPresetsExist(t *testing.T) {
	expected := []string{"coding-agent", "research-agent", "ci-agent", "devops-agent"}
	for _, id := range expected {
		p, err := FindPreset(id)
		if err != nil {
			t.Errorf("FindPreset(%q) failed: %v", id, err)
			continue
		}
		if p.ID != id {
			t.Errorf("FindPreset(%q).ID = %q, want %q", id, p.ID, id)
		}
		if p.Description == "" {
			t.Errorf("FindPreset(%q).Description is empty", id)
		}
	}
}

func TestFindPresetUnknown(t *testing.T) {
	_, err := FindPreset("nonexistent")
	if err == nil {
		t.Error("FindPreset(nonexistent) should return error")
	}
	if !strings.Contains(err.Error(), "unknown preset") {
		t.Errorf("error should mention 'unknown preset', got: %v", err)
	}
}

func TestRenderYAMLValid(t *testing.T) {
	for _, p := range Presets {
		yamlBytes, err := p.RenderYAML()
		if err != nil {
			t.Errorf("%s.RenderYAML() failed: %v", p.ID, err)
			continue
		}
		content := string(yamlBytes)
		if !strings.Contains(content, "version:") {
			t.Errorf("%s YAML missing version field", p.ID)
		}
		if !strings.Contains(content, "default_action:") {
			t.Errorf("%s YAML missing default_action field", p.ID)
		}
		if !strings.Contains(content, "# Generated by: rampart policy generate preset") {
			t.Errorf("%s YAML missing header comment", p.ID)
		}
	}
}

func TestRenderYAMLParseable(t *testing.T) {
	for _, p := range Presets {
		content, err := p.RenderYAML()
		if err != nil {
			t.Errorf("%s.RenderYAML() failed: %v", p.ID, err)
			continue
		}
		var parsed map[string]any
		if err := yaml.Unmarshal([]byte(content), &parsed); err != nil {
			t.Errorf("%s YAML not parseable: %v", p.ID, err)
		}
	}
}

func TestWriteToFileCreatesDir(t *testing.T) {
	dir := t.TempDir()
	dest := filepath.Join(dir, "nested", "deep", "policy.yaml")
	
	p, _ := FindPreset("coding-agent")
	if err := p.WriteToFile(dest, false); err != nil {
		t.Fatalf("WriteToFile failed: %v", err)
	}
	
	if _, err := os.Stat(dest); os.IsNotExist(err) {
		t.Error("file was not created")
	}
}

func TestWriteToFileNoOverwrite(t *testing.T) {
	dir := t.TempDir()
	dest := filepath.Join(dir, "policy.yaml")
	
	// Create existing file
	if err := os.WriteFile(dest, []byte("existing"), 0644); err != nil {
		t.Fatal(err)
	}
	
	p, _ := FindPreset("coding-agent")
	err := p.WriteToFile(dest, false)
	if err == nil {
		t.Error("WriteToFile should fail without --force when file exists")
	}
	if !strings.Contains(err.Error(), "exists") {
		t.Errorf("error should mention file exists, got: %v", err)
	}
}

func TestWriteToFileForceOverwrite(t *testing.T) {
	dir := t.TempDir()
	dest := filepath.Join(dir, "policy.yaml")
	
	// Create existing file
	if err := os.WriteFile(dest, []byte("existing"), 0644); err != nil {
		t.Fatal(err)
	}
	
	p, _ := FindPreset("coding-agent")
	if err := p.WriteToFile(dest, true); err != nil {
		t.Fatalf("WriteToFile with force=true failed: %v", err)
	}
	
	content, _ := os.ReadFile(dest)
	if strings.Contains(string(content), "existing") {
		t.Error("file was not overwritten")
	}
}

func TestPresetDefaultActions(t *testing.T) {
	cases := map[string]string{
		"coding-agent":   "default_action: allow",
		"research-agent": "default_action: deny",
		"ci-agent":       "default_action: deny",
		"devops-agent":   "default_action: deny",
	}
	for id, want := range cases {
		p, _ := FindPreset(id)
		yamlBytes, _ := p.RenderYAML()
		content := string(yamlBytes)
		if !strings.Contains(content, want) {
			t.Errorf("%s YAML should contain %q", id, want)
		}
	}
}

func TestCodingAgentBlocksCredentials(t *testing.T) {
	p, _ := FindPreset("coding-agent")
	yamlBytes, _ := p.RenderYAML()
	content := string(yamlBytes)
	
	// Should block credential paths
	if !strings.Contains(content, ".ssh") && !strings.Contains(content, "id_rsa") {
		t.Error("coding-agent should block SSH keys")
	}
	if !strings.Contains(content, ".aws") || !strings.Contains(content, ".env") {
		t.Error("coding-agent should block cloud credentials")
	}
}

func TestResearchAgentReadOnly(t *testing.T) {
	p, _ := FindPreset("research-agent")
	yamlBytes, _ := p.RenderYAML()
	content := string(yamlBytes)
	
	// Should allow read but not write
	if !strings.Contains(content, "read") {
		t.Error("research-agent should mention read tool")
	}
}

func TestDevopsAgentRequiresApproval(t *testing.T) {
	p, _ := FindPreset("devops-agent")
	yamlBytes, _ := p.RenderYAML()
	content := string(yamlBytes)
	
	if !strings.Contains(content, "require_approval") {
		t.Error("devops-agent should use require_approval for sensitive ops")
	}
}
