// Copyright 2026 The Rampart Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package generate provides preset policy templates for common agent use cases.
package generate

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/peg/rampart/internal/engine"
	"gopkg.in/yaml.v3"
)

// Preset describes a named policy template for a common agent use case.
type Preset struct {
	// ID is the machine-readable identifier (e.g. "coding-agent").
	ID string

	// Description is a short one-line summary shown in the selector menu.
	Description string

	// config is the policy configuration this preset generates.
	config engine.Config
}

// All available presets in display order.
var Presets = []Preset{
	CodingAgent,
	ResearchAgent,
	CIAgent,
	DevopsAgent,
}

// FindPreset returns the preset with the given ID, or an error if not found.
func FindPreset(id string) (Preset, error) {
	for _, p := range Presets {
		if p.ID == id {
			return p, nil
		}
	}
	return Preset{}, fmt.Errorf("generate: unknown preset %q (valid: coding-agent, research-agent, ci-agent, devops-agent)", id)
}

// RenderYAML serializes the preset's policy config to annotated YAML bytes.
func (p Preset) RenderYAML() ([]byte, error) {
	raw, err := yaml.Marshal(p.config)
	if err != nil {
		return nil, fmt.Errorf("generate: marshal preset %q: %w", p.ID, err)
	}
	header := fmt.Sprintf(
		"# Generated by: rampart policy generate preset\n"+
			"# Preset: %s — %s\n"+
			"# Generated: %s\n"+
			"# Edit this file to customise rules for your environment.\n\n",
		p.ID, p.Description,
		time.Now().UTC().Format(time.RFC3339),
	)
	return append([]byte(header), raw...), nil
}

// WriteToFile writes the preset YAML to dest, creating parent directories as
// needed. It refuses to overwrite an existing file unless force is true.
func (p Preset) WriteToFile(dest string, force bool) error {
	if err := os.MkdirAll(filepath.Dir(dest), 0o750); err != nil {
		return fmt.Errorf("generate: create directories for %s: %w", dest, err)
	}
	if !force {
		if _, err := os.Stat(dest); err == nil {
			return fmt.Errorf("generate: %s already exists; use --force to overwrite", dest)
		}
	}
	data, err := p.RenderYAML()
	if err != nil {
		return err
	}
	if err := os.WriteFile(dest, data, 0o640); err != nil {
		return fmt.Errorf("generate: write %s: %w", dest, err)
	}
	return nil
}

// ---------------------------------------------------------------------------
// Preset definitions
// ---------------------------------------------------------------------------

// CodingAgent allows file edits, common build and git tooling, and blocks
// access to credential files and outbound network fetches.
var CodingAgent = Preset{
	ID:          "coding-agent",
	Description: "File edits, git, build tools, block credentials",
	config: engine.Config{
		Version:       "1",
		DefaultAction: "allow",
		Policies: []engine.Policy{
			{
				Name:     "coding-block-credentials",
				Priority: 1,
				Match:    engine.Match{Tool: engine.StringOrSlice{"read", "edit"}},
				Rules: []engine.Rule{
					{
						Action: "deny",
						When: engine.Condition{
							PathMatches: []string{
								"**/.aws/credentials",
								"**/.aws/config",
								"**/.ssh/id_*",
								"**/.git-credentials",
								"**/.netrc",
								"**/.npmrc",
								"**/.pypirc",
								"**/.docker/config.json",
								"**/.kube/config",
								"**/.config/gcloud/**",
								"**/.gnupg/**",
								"**/Library/Keychains/**",
							},
							PathNotMatches: []string{
								"**/*.pub",
								"**/*.example",
							},
						},
						Message: "Credential file access blocked",
					},
					{
						Action: "deny",
						When: engine.Condition{
							PathMatches: []string{
								"**/.env",
								"**/.env.local",
								"**/.env.production",
								"**/.env.*.local",
								"**/.envrc",
							},
							PathNotMatches: []string{
								"**/.env.example",
								"**/.env.sample",
								"**/.env.test",
							},
						},
						Message: "Environment file access blocked",
					},
				},
			},
			{
				Name:     "coding-block-network-fetch",
				Priority: 2,
				Match:    engine.Match{Tool: engine.StringOrSlice{"exec"}},
				Rules: []engine.Rule{
					{
						Action: "deny",
						When: engine.Condition{
							CommandMatches: []string{
								"curl *",
								"wget *",
								"nc *",
								"ncat *",
								"ssh-keyscan *",
							},
						},
						Message: "Outbound network commands blocked for coding agent",
					},
				},
			},
			{
				Name:     "coding-allow-tools",
				Priority: 10,
				Match:    engine.Match{Tool: engine.StringOrSlice{"exec"}},
				Rules: []engine.Rule{
					{
						Action: "allow",
						When: engine.Condition{
							CommandMatches: []string{
								// Git
								"git status", "git diff *", "git log *", "git show *",
								"git add *", "git commit *", "git checkout *", "git branch *",
								"git stash *", "git merge *", "git rebase *", "git fetch *",
								"git pull *", "git push *", "git clone *", "git tag *",
								// Build / test – Go
								"go build *", "go test *", "go run *", "go vet *",
								"go fmt *", "go mod *", "go generate *", "go install *",
								"golangci-lint *", "govulncheck *",
								// Build / test – Node
								"npm run *", "npm test *", "npm install", "npm ci",
								"npx *", "pnpm run *", "pnpm test *", "yarn *",
								// Build / test – Python
								"python *", "python3 *", "pip install *", "pip3 install *",
								"pytest *", "ruff *", "mypy *", "black *",
								// Build / test – Rust
								"cargo build *", "cargo test *", "cargo run *", "cargo fmt *",
								"cargo clippy *", "cargo check *",
								// Make / shell utilities
								"make *", "just *", "sh *", "bash *",
								"ls *", "find *", "grep *", "cat *", "head *", "tail *",
								"echo *", "printf *", "mkdir *", "cp *", "mv *",
								"touch *", "chmod *", "diff *", "sort *", "uniq *",
							},
						},
						Message: "Common coding tool allowed",
					},
				},
			},
			{
				Name:     "coding-watch-installs",
				Priority: 20,
				Match:    engine.Match{Tool: engine.StringOrSlice{"exec"}},
				Rules: []engine.Rule{
					{
						Action: "watch",
						When: engine.Condition{
							CommandMatches: []string{
								"npm install *",
								"pnpm add *",
								"yarn add *",
								"pip install *",
								"pip3 install *",
								"cargo add *",
								"go get *",
							},
						},
						Message: "Package installation logged for review",
					},
				},
			},
		},
	},
}

// ResearchAgent allows web fetching and file reading but blocks all writes and
// shell commands that modify state.
var ResearchAgent = Preset{
	ID:          "research-agent",
	Description: "Web fetch, file read, no writes",
	config: engine.Config{
		Version:       "1",
		DefaultAction: "deny",
		Policies: []engine.Policy{
			{
				Name:     "research-allow-fetch",
				Priority: 1,
				Match:    engine.Match{Tool: engine.StringOrSlice{"fetch", "web_search", "browser"}},
				Rules: []engine.Rule{
					{
						Action:  "allow",
						When:    engine.Condition{Default: true},
						Message: "Web fetch allowed for research agent",
					},
				},
			},
			{
				Name:     "research-allow-read",
				Priority: 2,
				Match:    engine.Match{Tool: engine.StringOrSlice{"read"}},
				Rules: []engine.Rule{
					{
						Action: "deny",
						When: engine.Condition{
							PathMatches: []string{
								"**/.aws/**",
								"**/.ssh/**",
								"**/.env",
								"**/.env.local",
								"**/.env.production",
								"**/.git-credentials",
								"**/.netrc",
								"**/.gnupg/**",
								"**/Library/Keychains/**",
							},
						},
						Message: "Sensitive file reads blocked for research agent",
					},
					{
						Action:  "allow",
						When:    engine.Condition{Default: true},
						Message: "File read allowed for research agent",
					},
				},
			},
			{
				Name:     "research-block-writes",
				Priority: 3,
				Match:    engine.Match{Tool: engine.StringOrSlice{"write", "edit"}},
				Rules: []engine.Rule{
					{
						Action:  "deny",
						When:    engine.Condition{Default: true},
						Message: "File writes blocked: research agent is read-only",
					},
				},
			},
			{
				Name:     "research-allow-readonly-exec",
				Priority: 4,
				Match:    engine.Match{Tool: engine.StringOrSlice{"exec"}},
				Rules: []engine.Rule{
					{
						Action: "allow",
						When: engine.Condition{
							CommandMatches: []string{
								"ls *", "ls", "find *", "grep *", "cat *",
								"head *", "tail *", "wc *", "echo *",
								"pwd", "date", "whoami", "id",
								"rg *", "fd *", "bat *",
							},
						},
						Message: "Read-only command allowed for research agent",
					},
					{
						Action:  "deny",
						When:    engine.Condition{Default: true},
						Message: "Exec blocked: research agent allows read-only commands only",
					},
				},
			},
		},
	},
}

// CIAgent allows build and test commands but blocks all network access and
// credential file reads to keep CI pipelines safe and hermetic.
var CIAgent = Preset{
	ID:          "ci-agent",
	Description: "Build/test only, no network, no secrets",
	config: engine.Config{
		Version:       "1",
		DefaultAction: "deny",
		Policies: []engine.Policy{
			{
				Name:     "ci-block-secrets",
				Priority: 1,
				Match:    engine.Match{Tool: engine.StringOrSlice{"read", "edit"}},
				Rules: []engine.Rule{
					{
						Action: "deny",
						When: engine.Condition{
							PathMatches: []string{
								"**/.aws/**",
								"**/.ssh/id_*",
								"**/.git-credentials",
								"**/.netrc",
								"**/.npmrc",
								"**/.pypirc",
								"**/.docker/config.json",
								"**/.kube/config",
								"**/.config/gcloud/**",
								"**/.gnupg/**",
								"**/Library/Keychains/**",
								"**/.env",
								"**/.env.local",
								"**/.env.production",
								"**/.envrc",
							},
							PathNotMatches: []string{
								"**/*.pub",
								"**/*.example",
								"**/.env.test",
								"**/.env.ci",
							},
						},
						Message: "Secret file access blocked in CI",
					},
				},
			},
			{
				Name:     "ci-block-network",
				Priority: 2,
				Match:    engine.Match{Tool: engine.StringOrSlice{"exec", "fetch"}},
				Rules: []engine.Rule{
					{
						Action: "deny",
						When: engine.Condition{
							CommandMatches: []string{
								"curl *", "wget *", "nc *", "ncat *",
								"ssh *", "scp *", "rsync *",
								"git clone *", "git fetch *", "git pull *", "git push *",
							},
						},
						Message: "Network access blocked in CI",
					},
				},
			},
			{
				Name:     "ci-allow-build-test",
				Priority: 10,
				Match:    engine.Match{Tool: engine.StringOrSlice{"exec"}},
				Rules: []engine.Rule{
					{
						Action: "allow",
						When: engine.Condition{
							CommandMatches: []string{
								// Go
								"go build *", "go test *", "go vet *", "go generate *",
								"go mod tidy", "go mod verify", "go mod download",
								"golangci-lint *", "govulncheck *",
								// Node
								"npm run *", "npm test *", "npm ci", "npm install",
								"npx *", "pnpm run *", "pnpm test *", "yarn test *",
								// Python
								"python -m pytest *", "python3 -m pytest *",
								"pytest *", "python -m *", "python3 -m *",
								"ruff *", "mypy *", "black --check *",
								// Rust
								"cargo build *", "cargo test *", "cargo check *",
								"cargo clippy *", "cargo fmt --check *",
								// Make / shell basics
								"make *", "just *",
								"ls *", "find *", "grep *", "cat *", "echo *",
								"mkdir *", "cp *", "mv *", "rm *", "chmod *",
								"diff *", "sort *", "uniq *", "sed *", "awk *",
								"git status", "git diff *", "git log *",
								"git add *", "git commit *", "git checkout *",
								"git stash *", "git merge *", "git tag *",
							},
						},
						Message: "Build/test command allowed in CI",
					},
				},
			},
			{
				Name:     "ci-allow-read",
				Priority: 20,
				Match:    engine.Match{Tool: engine.StringOrSlice{"read"}},
				Rules: []engine.Rule{
					{
						Action:  "allow",
						When:    engine.Condition{Default: true},
						Message: "File read allowed in CI",
					},
				},
			},
			{
				Name:     "ci-allow-write",
				Priority: 20,
				Match:    engine.Match{Tool: engine.StringOrSlice{"write", "edit"}},
				Rules: []engine.Rule{
					{
						Action:  "allow",
						When:    engine.Condition{Default: true},
						Message: "File write allowed in CI build directories",
					},
				},
			},
		},
	},
}

// DevopsAgent allows common devops tooling (docker, kubectl, helm, ssh) with
// human approval required for any state-changing operations.
var DevopsAgent = Preset{
	ID:          "devops-agent",
	Description: "Docker, kubectl, ssh (with approval)",
	config: engine.Config{
		Version:       "1",
		DefaultAction: "deny",
		Policies: []engine.Policy{
			{
				Name:     "devops-approve-kubectl-write",
				Priority: 1,
				Match:    engine.Match{Tool: engine.StringOrSlice{"exec"}},
				Rules: []engine.Rule{
					{
						Action: "require_approval",
						When: engine.Condition{
							CommandMatches: []string{
								"kubectl apply *",
								"kubectl delete *",
								"kubectl patch *",
								"kubectl rollout restart *",
								"kubectl scale *",
								"kubectl drain *",
								"kubectl cordon *",
								"kubectl uncordon *",
								"kubectl create *",
								"kubectl replace *",
								"kubectl set *",
							},
						},
						Message: "kubectl write operation requires human approval",
					},
					{
						Action: "allow",
						When: engine.Condition{
							CommandMatches: []string{
								"kubectl get *",
								"kubectl describe *",
								"kubectl logs *",
								"kubectl top *",
								"kubectl explain *",
								"kubectl config *",
								"kubectl version *",
								"kubectl cluster-info *",
								"kubectl events *",
							},
						},
						Message: "kubectl read-only operation allowed",
					},
				},
			},
			{
				Name:     "devops-approve-helm-write",
				Priority: 2,
				Match:    engine.Match{Tool: engine.StringOrSlice{"exec"}},
				Rules: []engine.Rule{
					{
						Action: "require_approval",
						When: engine.Condition{
							CommandMatches: []string{
								"helm install *",
								"helm upgrade *",
								"helm uninstall *",
								"helm rollback *",
								"helm delete *",
							},
						},
						Message: "Helm deployment requires human approval",
					},
					{
						Action: "allow",
						When: engine.Condition{
							CommandMatches: []string{
								"helm list *", "helm status *", "helm get *",
								"helm history *", "helm template *", "helm repo *",
								"helm search *", "helm show *", "helm version",
							},
						},
						Message: "Helm read-only operation allowed",
					},
				},
			},
			{
				Name:     "devops-approve-terraform",
				Priority: 3,
				Match:    engine.Match{Tool: engine.StringOrSlice{"exec"}},
				Rules: []engine.Rule{
					{
						Action: "require_approval",
						When: engine.Condition{
							CommandMatches: []string{
								"terraform apply *",
								"terraform destroy *",
								"terraform import *",
								"terraform state *",
							},
						},
						Message: "Terraform apply/destroy requires human approval",
					},
					{
						Action: "allow",
						When: engine.Condition{
							CommandMatches: []string{
								"terraform plan *", "terraform init *",
								"terraform validate *", "terraform fmt *",
								"terraform show *", "terraform output *",
								"terraform version", "terraform providers *",
							},
						},
						Message: "Terraform read-only operation allowed",
					},
				},
			},
			{
				Name:     "devops-approve-ssh",
				Priority: 4,
				Match:    engine.Match{Tool: engine.StringOrSlice{"exec"}},
				Rules: []engine.Rule{
					{
						Action: "require_approval",
						When: engine.Condition{
							CommandMatches: []string{
								"ssh *",
								"scp *",
								"rsync *",
								"ansible *",
								"ansible-playbook *",
							},
						},
						Message: "Remote shell/transfer requires human approval",
					},
				},
			},
			{
				Name:     "devops-approve-docker-push",
				Priority: 5,
				Match:    engine.Match{Tool: engine.StringOrSlice{"exec"}},
				Rules: []engine.Rule{
					{
						Action: "require_approval",
						When: engine.Condition{
							CommandMatches: []string{
								"docker push *",
								"docker rm *",
								"docker rmi *",
								"docker network rm *",
								"docker volume rm *",
							},
						},
						Message: "Docker destructive operation requires human approval",
					},
					{
						Action: "allow",
						When: engine.Condition{
							CommandMatches: []string{
								"docker build *",
								"docker run *",
								"docker ps *",
								"docker images *",
								"docker logs *",
								"docker exec *",
								"docker inspect *",
								"docker pull *",
								"docker tag *",
								"docker compose *",
								"docker-compose *",
							},
						},
						Message: "Docker operation allowed",
					},
				},
			},
			{
				Name:     "devops-allow-readonly",
				Priority: 10,
				Match:    engine.Match{Tool: engine.StringOrSlice{"exec"}},
				Rules: []engine.Rule{
					{
						Action: "allow",
						When: engine.Condition{
							CommandMatches: []string{
								"ls *", "find *", "grep *", "cat *", "head *", "tail *",
								"ps *", "top", "htop", "df *", "du *", "free *",
								"systemctl status *", "journalctl *",
								"netstat *", "ss *", "lsof *",
								"echo *", "date", "whoami", "id", "hostname",
								"git *", "make *",
							},
						},
						Message: "Read-only system command allowed",
					},
				},
			},
			{
				Name:     "devops-allow-read-write",
				Priority: 20,
				Match:    engine.Match{Tool: engine.StringOrSlice{"read", "write", "edit"}},
				Rules: []engine.Rule{
					{
						Action: "deny",
						When: engine.Condition{
							PathMatches: []string{
								"**/.ssh/id_*",
								"**/.aws/credentials",
								"**/.git-credentials",
								"**/.netrc",
								"**/.gnupg/**",
							},
							PathNotMatches: []string{"**/*.pub"},
						},
						Message: "Private key/credential access blocked",
					},
					{
						Action:  "allow",
						When:    engine.Condition{Default: true},
						Message: "File access allowed for devops agent",
					},
				},
			},
		},
	},
}
