// Copyright 2026 The Rampart Authors
// Licensed under the Apache License, Version 2.0 (the "License").

package generate

import (
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/peg/rampart/internal/engine"
)

func TestAllPresetsExist(t *testing.T) {
	for _, id := range []string{"coding-agent", "research-agent", "ci-agent", "devops-agent"} {
		t.Run(id, func(t *testing.T) {
			p, err := FindPreset(id)
			if err != nil {
				t.Fatal(err)
			}
			if p.ID != id || p.Description == "" {
				t.Fatalf("FindPreset(%q) = %+v, want matching ID and description", id, p)
			}
		})
	}
}

func TestFindPresetUnknown(t *testing.T) {
	for _, id := range []string{"nonexistent", ""} {
		t.Run(id, func(t *testing.T) {
			_, err := FindPreset(id)
			if err == nil {
				t.Fatal("expected an unknown-preset error")
			}
			if !strings.Contains(err.Error(), "unknown preset") || !strings.Contains(err.Error(), "coding-agent") {
				t.Fatalf("error must identify the problem and an available preset: %v", err)
			}
		})
	}
}

func TestRenderYAMLValid(t *testing.T) {
	defaultActions := map[string]string{
		"coding-agent": "allow", "research-agent": "deny", "ci-agent": "deny", "devops-agent": "deny",
	}
	for _, p := range Presets {
		t.Run(p.ID, func(t *testing.T) {
			data, err := p.RenderYAML()
			if err != nil {
				t.Fatal(err)
			}
			cfg, err := engine.NewMemoryStore(data, "preset:"+p.ID).Load()
			if err != nil {
				t.Fatalf("rendered YAML must load through the engine: %v", err)
			}
			if cfg.Version != "1" || len(cfg.Policies) == 0 || cfg.DefaultAction != defaultActions[p.ID] {
				t.Fatalf("unexpected rendered config: version=%q policies=%d default=%q", cfg.Version, len(cfg.Policies), cfg.DefaultAction)
			}
			for _, header := range []string{"# Generated by: rampart policy generate preset", p.ID, p.Description} {
				if !strings.Contains(string(data), header) {
					t.Errorf("rendered header missing %q", header)
				}
			}
		})
	}
}

func TestWriteToFile(t *testing.T) {
	for _, tc := range []struct {
		name, preset, path, content string
		exists, force               bool
	}{
		{name: "create", preset: "coding-agent", path: "policy.yaml", content: "coding-block-credentials"},
		{name: "create parents", preset: "devops-agent", path: "nested/deep/policy.yaml", content: "devops-approve-kubectl-write"},
		{name: "refuse overwrite", preset: "coding-agent", path: "policy.yaml", exists: true},
		{name: "force overwrite", preset: "ci-agent", path: "policy.yaml", content: "ci-block-secrets", exists: true, force: true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			dest := filepath.Join(t.TempDir(), filepath.FromSlash(tc.path))
			if tc.exists {
				if err := os.WriteFile(dest, []byte("existing"), 0o600); err != nil {
					t.Fatal(err)
				}
			}
			p, err := FindPreset(tc.preset)
			if err != nil {
				t.Fatal(err)
			}
			err = p.WriteToFile(dest, tc.force)
			if tc.exists && !tc.force {
				if err == nil || !strings.Contains(err.Error(), "already exists") {
					t.Fatalf("expected overwrite refusal, got %v", err)
				}
				data, readErr := os.ReadFile(dest)
				if readErr != nil || string(data) != "existing" {
					t.Fatalf("refused write changed existing file: %q, %v", data, readErr)
				}
				return
			}
			if err != nil {
				t.Fatal(err)
			}
			data, err := os.ReadFile(dest)
			if err != nil {
				t.Fatal(err)
			}
			if !strings.Contains(string(data), p.ID) || !strings.Contains(string(data), tc.content) {
				t.Fatalf("file does not contain the selected preset %q", p.ID)
			}
			if _, err := engine.NewMemoryStore(data, "preset:"+p.ID).Load(); err != nil {
				t.Fatalf("written policy does not load: %v", err)
			}
		})
	}
}

func TestPresetDecisions(t *testing.T) {
	type callCase struct {
		tool, param, value string
		want               engine.Action
		matchedPolicy      string
	}
	for _, tc := range []struct {
		preset string
		calls  []callCase
	}{
		{"coding-agent", []callCase{
			{"read", "path", ".aws/credentials", engine.ActionDeny, "coding-block-credentials"},
			{"read", "path", ".aws/credentials.example", engine.ActionAllow, ""},
			{"read", "path", ".ssh/id_ed25519", engine.ActionDeny, "coding-block-credentials"},
			{"read", "path", ".ssh/id_ed25519.pub", engine.ActionAllow, ""},
			{"read", "path", ".env", engine.ActionDeny, "coding-block-credentials"},
			{"read", "path", ".env.example", engine.ActionAllow, ""},
		}},
		{"research-agent", []callCase{
			{"write", "path", "notes.txt", engine.ActionDeny, "research-block-writes"},
			{"edit", "path", "notes.txt", engine.ActionDeny, "research-block-writes"},
			{"read", "path", "notes.txt", engine.ActionAllow, ""},
		}},
		{"ci-agent", []callCase{
			{"exec", "command", "curl https://example.invalid", engine.ActionDeny, "ci-block-network"},
			{"exec", "command", "wget https://example.invalid", engine.ActionDeny, "ci-block-network"},
			{"exec", "command", "go test ./...", engine.ActionAllow, ""},
		}},
		{"devops-agent", []callCase{
			{"exec", "command", "kubectl apply -f deployment.yaml", engine.ActionAsk, "devops-approve-kubectl-write"},
			{"exec", "command", "kubectl get deployments", engine.ActionAllow, ""},
			{"exec", "command", "ssh example.invalid", engine.ActionAsk, "devops-approve-ssh"},
		}},
	} {
		t.Run(tc.preset, func(t *testing.T) {
			p, err := FindPreset(tc.preset)
			if err != nil {
				t.Fatal(err)
			}
			data, err := p.RenderYAML()
			if err != nil {
				t.Fatal(err)
			}
			e, err := engine.New(engine.NewMemoryStore(data, "preset:"+p.ID), slog.New(slog.NewTextHandler(io.Discard, nil)))
			if err != nil {
				t.Fatal(err)
			}
			dir := t.TempDir()
			for _, call := range tc.calls {
				t.Run(call.tool+" "+call.value, func(t *testing.T) {
					value := call.value
					if call.param == "path" {
						value = filepath.Join(dir, filepath.FromSlash(value))
					}
					// Only evaluate represented calls; no command runs or target file reads.
					got := e.Evaluate(engine.ToolCall{Tool: call.tool, Params: map[string]any{call.param: value}})
					if got.Action != call.want {
						t.Fatalf("decision = %s, want %s (%s)", got.Action, call.want, got.Message)
					}
					if call.matchedPolicy != "" && !slices.Contains(got.MatchedPolicies, call.matchedPolicy) {
						t.Fatalf("matched policies = %v, want %s", got.MatchedPolicies, call.matchedPolicy)
					}
				})
			}
		})
	}
}
